### ISSUE TITLE
Vyhledavani budov

### ISSUE THREAD

**Issue by bambuste** [ctu-geoforall-lab/qgis-vfk-plugin-old#10]

**Comment by bambuste** [comment]
doplnena funkcionalita vypisu budov do browseru..

**Comment by bambuste** [comment]
vyhledavani funkcni cca na 90% - nefunkcni nacitani/vyber z comboboxu

**Comment by bambuste** [comment]
funkcni vyhledavani pomoci ComboBoxu

**Comment by landam** [comment]
povrzuji
