### ISSUE TITLE
Vyhledavani jednotek

### ISSUE THREAD

**Issue by bambuste** [ctu-geoforall-lab/qgis-vfk-plugin-old#11]

**Comment by bambuste** [comment]
doplnena funkcionalita vypisu jednotek do browseru..

**Comment by bambuste** [comment]
vyhledavani funkcni cca na 90% - nefunkcni nacitani/vyber z comboboxu

**Comment by bambuste** [comment]
funkcni vyhledavani pomoxi ComboBoxu

**Comment by landam** [comment]
potvrzuji...
