### ISSUE TITLE
Export do html

### ISSUE THREAD

**Issue by bambuste** [ctu-geoforall-lab/qgis-vfk-plugin-old#15]

**Comment by bambuste** [comment]
implementovano

**Comment by landam** [comment]
Pokud vystupni soubor nekonci na priponu .html, tak by mela byt automaticky pridana.

**Comment by landam** [comment]
uzivatel by mozna take ocekaval nejake potvrzovaci okno, ze export probehl v poradku.

**Comment by bambuste** [comment]
pridano

**Comment by landam** [comment]
Po stisknuti tlacitka Cancel plugin informuje o uspesnem exportu.

**Comment by landam** [comment]
potvrzuji...
