### ISSUE TITLE
Export do latex

### ISSUE THREAD

**Issue by bambuste** [ctu-geoforall-lab/qgis-vfk-plugin-old#16]

**Comment by bambuste** [comment]
Export byl implementován, ale v budoucnu je ještě potřeba upravit vzhled tabulek.

**Comment by bambuste** [comment]
pridano automaticke doplneni pripony, potvrzovanci box o uspesnem exportu

**Comment by bambuste** [comment]
funkcni

**Comment by landam** [comment]
Po stisknuti tlacitka Cancel plugin informuje o uspesnem exportu.

**Comment by landam** [comment]
potvrzuji...
