### ISSUE TITLE
funkcni odkazy v browseru

### ISSUE THREAD

**Issue by bambuste** [ctu-geoforall-lab/qgis-vfk-plugin-old#19]

**Comment by bambuste** [comment]
melo by fungovat..

**Comment by landam** [comment]
co presne je tim mysleno? chybi blizsi popis...

**Comment by bambuste** [comment]
myšleno listování mezi odkazy v samotném browseru, např. zobrazení listu vlastnictvi z vyhledanych parcel, zobrazeni sousednich parcel, ..

**Comment by landam** [comment]
potvrzuji...
