### ISSUE TITLE
funkcnost vyhledavani

### ISSUE THREAD

**Issue by landam** [ctu-geoforall-lab/qgis-vfk-plugin-old#3]
V soucasne dobe dialog pro vyhledavani (parcely, vlasntnici) nezobrazuje relevatni informace z vstupniho VFK souboru.

**Comment by bambuste** [comment]
nacteni dat ze vstupniho souboru do vyhledavacich ComboBoxu bylo pridano. Pro samotnou funkcionalitu vyhledavani byly vytvoreny nove ukoly

**Comment by landam** [comment]
vypada to, ze ne vse funguje korektne, viz porovnani 

c++ pluginu:

![c++ pluginu](http://geo102.fsv.cvut.cz/~landa/tmp/vfk-cpp.png)

a python verze:

![python pluginu](http://geo102.fsv.cvut.cz/~landa/tmp/vfk-py.png)

**Comment by bambuste** [comment]
opraveno spravne nacitani hodnot do ComboBoxu na zaklade nactenych dat

**Comment by landam** [comment]
potvrzuji
