### ISSUE TITLE
pojmenovani DB na zaklade toho, zda se jedna o stavova anebo zmenova data

### ISSUE THREAD

**Issue by landam** [ctu-geoforall-lab/qgis-vfk-plugin-old#31]
Bude vyzadovat otevreni VFK souboru v pluginu a zpracovani hlavicky.

**Comment by bambuste** [comment]
V commitu [bffcca7](https://github.com/ctu-osgeorel/qgis-vfk-plugin/commit/bffcca72ad4791da43b2594ba87c8b915be0af24) vyreseno pri cteni z VFK souboru.
