### ISSUE TITLE
Pro parcely, kde PODDELENI_CISLA_PAR = NULL, se nezobrazuje popisek obsahujici cislo parcely

### ISSUE THREAD

**Issue by bambuste** [ctu-geoforall-lab/qgis-vfk-plugin-old#34]
Viz e-mail od Fiala Lukáš ze dne 11.5.

**Comment by landam** [comment]
@bambuste planujes backport do release-2_0?

**Comment by bambuste** [comment]
@landam ted ho tam zrovna posilam

**Comment by landam** [comment]
@bambuste : pozor je tam konflikt!

**Comment by bambuste** [comment]
@landam Pracuji na odstraneni..

**Comment by bambuste** [comment]
@landam Vyreseno, udelal jsem i backport do release-2_0. Vse by melo fungovat
