### ISSUE TITLE
Přidat checkbox pro přepsání stávající DB před importem dat

### ISSUE THREAD

**Issue by bambuste** [ctu-geoforall-lab/qgis-vfk-plugin-old#36]
Jestliže je checkbox zaškrtnut, tak vyexportovat proměnnou `OGR_VFK_DB_OVERWRITE=1` a přepsat stávající DB

**Comment by bambuste** [comment]
Jestliže je checkbox zaškrtnut, tak vyexportovat proměnnou `OGR_VFK_DB_OVERWRITE=1` a přepsat db

**Comment by landam** [comment]
Zmenit UI, tak aby 'Moznosti:' byly tesne po 'Vrstvy:', tj. pridal vertikalni spacer az za 'Moznosti'.

**Comment by landam** [comment]
@bambuste pri zaskrtnuti volby prepsani db to navic vypada, ze driver znovuvytvari databazi pri kazdem posunu nebo zmene pohledu. Promenna prostredi OGR_VFK_DB_OVERWRITE by mela byt aplikovana pouze pri otevreni datasource.
