### ISSUE TITLE
Není kompatibilní s verzí QGIS 3.0 a výše

### ISSUE THREAD

**Issue by vysmaty** [ctu-geoforall-lab/qgis-vfk-plugin-old#40]
Nalezl jsem nějaké nástroje. Ale je to mimo mé znalosti. http://www.opengis.ch/2018/04/13/porting-qgis-plugins-to-api-v3-strategy-and-tools/ 
![image](https://user-images.githubusercontent.com/10959584/44298037-2ad66a80-a2dc-11e8-881e-edc627e76188.png)

**Comment by landam** [comment]
Ano, VFK Plugin je dostupny pouze pro QGIS 2.x. Aktualizace pro QGIS 3.x je v planu.

**Comment by landam** [comment]
@vysmaty Experimentalni podpora pro QGIS3 je ted dostupna v masteru #41
