### ISSUE TITLE
Vyhledavani vlastniku

### ISSUE THREAD

**Issue by bambuste** [ctu-geoforall-lab/qgis-vfk-plugin-old#8]

**Comment by bambuste** [comment]
castecne funkcni: nefunguje combobox, spatne kodovani ve vypisu do browseru

**Comment by bambuste** [comment]
vyhledavani funkcni cca na 90% - nefunguje checkbox OPO

**Comment by bambuste** [comment]
funkcni

**Comment by landam** [comment]
potvrzuji...
