### ISSUE TITLE
Vyhledavani parcel

### ISSUE THREAD

**Issue by bambuste** [ctu-geoforall-lab/qgis-vfk-plugin-old#9]

**Comment by bambuste** [comment]
V soucasne chvili je doplnena funkcionalita vypisu parcel do browseru..

**Comment by bambuste** [comment]
vyhledavani funkcni cca na 90% - nefunkcni nacitani/vyber z comboboxu

**Comment by bambuste** [comment]
implemetovano vyhledavani pomoci comboboxu

**Comment by landam** [comment]
potvrzuji...
